# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: false

    - name: Check code format
      run: test -z "$(gofmt -l ./)"

    - name: Check code lint
      run: make code-lint

    - name: Golang CI - Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --verbose
